#!/bin/sh

base_level="$(git rev-parse --show-toplevel)" || exit 1
cd "$base_level" || exit 1
branch="$(git branch --show)"
if [ "$branch" = "dist" ] ; then
    git checkout main || exit 2
    branch=main
fi

_cook() {
    count="$(git rev-list "$branch" --count --since="$(date --utc +@%s --date="$(date --utc '+%Y-%m-%d 00:00')")")"
    version_date="$(date --utc '+%Y.%m.%d')"
    sed -E "s/BAKE_VERSION/${version_date}.${count}/g" \
        <traneptora-roll20-fixes.meta.in.js >traneptora-roll20-fixes.meta.js
    printf '\n' >>traneptora-roll20-fixes.meta.js
    cat traneptora-roll20-fixes.meta.js traneptora-roll20-fixes.in.js \
        >traneptora-roll20-fixes.user.js
}

git checkout dist
rm -f -- traneptora-roll20-fixes.meta.js traneptora-roll20-fixes.user.js
git add -v traneptora-roll20-fixes.meta.js traneptora-roll20-fixes.user.js
git commit -m "commit: $(date -u -Is)"
git checkout "$branch"

_cook

git checkout dist
git add -v traneptora-roll20-fixes.meta.js traneptora-roll20-fixes.user.js
git commit --fixup=HEAD
git rebase --autosquash
git push --force origin dist
git checkout "$branch"
rm -f -- traneptora-roll20-fixes.meta.js traneptora-roll20-fixes.user.js
